/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.BaseDatos;
import Controlador.LeoNoticias;
import Controlador.LeonOcio;
import Controlador.Minube;
import Controlador.Terranostrum;
import Controlador.Yumping;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class NewJFrame extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame
	 */
	public NewJFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane2 = new javax.swing.JScrollPane();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		label= new JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		Desactivar = new javax.swing.JButton();
		Activar = new javax.swing.JButton();
		jComboBox = new JComboBox<String>();
		seleccionado="Todo";
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
		jLabel1.setText("Web Scraper");
		jTextArea1.setEditable(false);
		jTextArea1.setColumns(20);
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(5);
		jTextArea1.setTabSize(6);
		jScrollPane1.setViewportView(jTextArea1);

		Desactivar.setText("Desactivar");
		Desactivar.setEnabled(false);
		Desactivar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton3MouseClicked(evt);
			}
		});

		Activar.setText("Activar");
		Activar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton4MouseClicked(evt);
			}
		});

		jComboBox.setBounds(450,17,100,30); 
		add(jComboBox);
		jComboBox.addItem("Todo");
		jComboBox.addItem("Noticias");
		jComboBox.addItem("Eventos");
		jComboBox.addItem("Actividades");
		jComboBox.addItem("Rutas");
		jComboBox.addItem("Hoteles");
		jComboBox.addItem("Deportes");
		jComboBox.addItem("Parques");
		jComboBox.addItem("Restaurantes");
		jComboBox.addItem("Cultura");
		jComboBox.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				 if (e.getSource()==jComboBox) {
			            seleccionado=(String)jComboBox.getSelectedItem();
			            System.out.println(seleccionado);
			           //System.out.println(hilo.toString());
			        if(hilo!=null) {
			           if(seleccionado.equals("Todo")) {
			            if(hilo.isAlive()==true) {
			            	System.out.println(hilo.isAlive());
			            	Desactivar.setEnabled(true);
				            Activar.setEnabled(false);
			            }else{
			            	System.out.println(hilo.isAlive());
			            	Desactivar.setEnabled(false);
				            Activar.setEnabled(true);
			            }
			        }
			        }
			            if(!seleccionado.equals("Todo")) {
			            	
				            	 Desactivar.setEnabled(false);
						         Activar.setEnabled(true);
				            }
			            
			          
			            
			        }
				
			}
		});
		
		

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(
										jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(22, 22, 22)
										.addComponent(Activar, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(Desactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(17, 17, 17)))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(174, 174, 174).addComponent(jLabel1)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1).addGap(17, 17, 17)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(Activar, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(Desactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(9, 9, 9)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(17, Short.MAX_VALUE)));

		pack();
	}


	private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton4MouseClicked
		// TODO add your handling code here:

		jTextArea1.setText("Web scraper activado\n");

		oBD = new BaseDatos();
		jTextArea1.append("Se ha conectado con la base de datos\n");
		
		if(seleccionado.equals("Todo")||seleccionado==null) {
		Runnable runnable = new Runnable() {
			@Override
			public void run() {
				Desactivar.setEnabled(true);
				while (detener) {
				
					
					try {

						Date d = new Date();
						jTextArea1.append("Fecha de ejecucion Web Scraper-Noticias: " + d.toString() + "\n");
						LeoNoticias not = new LeoNoticias(oBD);
						jTextArea1.append("Se han introducido en la base de datos " + not.getContadorNoticias()
								+ " nuevas Noticias\n");
						Thread.sleep((long) 3.6e+6);

					} catch (InterruptedException e) {
						e.printStackTrace();
					}
				}
			}
		};
		
		Runnable r = new Runnable() {
			@Override
			public void run() {
				Desactivar.setEnabled(true);
				while (detener) {
					
					Date d = new Date();
					System.out.println(d.toString());
					jTextArea1.append("Fecha de ejecucion Web Scraper-Contenido: " + d.toString() + "\n");
					Yumping yump = new Yumping(oBD);
					LeonOcio leonO = new LeonOcio(oBD,seleccionado);
					Terranostrum Terra = new Terranostrum(oBD,seleccionado);
					Minube minube = new Minube(oBD);
					int resultado = leonO.getContadorCultura() + Terra.getContadorCultura();
					jTextArea1.append("Se han introducido en la base de datos " + yump.getContadorAct()
							+ " nuevas Actividades\n");
					jTextArea1.append("Se han introducido en la base de datos " + resultado
							+ " nuevos lugares de interes cultural\n");
					jTextArea1.append("Se han introducido en la base de datos " + leonO.getContadorDepor()
							+ " nuevas instalaciones deportivas\n");
					jTextArea1.append("Se han introducido en la base de datos " + leonO.getContadorEvenros()
							+ " nuevos Eventos\n");
					jTextArea1.append(
							"Se han introducido en la base de datos " + leonO.getContadorHotel() + " nuevos Hoteles\n");
					resultado = leonO.getContadorParques() + minube.getContadorParq();
					jTextArea1.append("Se han introducido en la base de datos " + resultado + " nuevas Parques\n");
					resultado = leonO.getContadorRutas() + Terra.getContadorRutas();
					jTextArea1.append("Se han introducido en la base de datos " + resultado + " nuevas Rutas\n");
					jTextArea1.append("Se han introducido en la base de datos " + leonO.getContadorrestau()
							+ " nuevos Restaurantes\n");
					try {
						Thread.sleep((long) 8.64e+7);
					} catch (InterruptedException ex) {
						Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
					}
					
				}
				jTextArea1.append("Se ha desactivado el Web Scraper\n");
			}
		};
		hilo = new Thread(runnable);
		hilo2 = new Thread(r);
		hilo.start();
		hilo2.start();
		}else {
		
		Runnable sel = new Runnable() {
	
			
			public void run() {
				Desactivar.setEnabled(false);
				 jComboBox.setEnabled(false);
				if(seleccionado.equals("Noticias")) {
					
					LeoNoticias not = new LeoNoticias(oBD);
					jTextArea1.append("Se han introducido en la base de datos " + not.getContadorNoticias()
							+ " nuevas Noticias\n");
				}
				if(seleccionado.equals("Eventos")) {
					LeonOcio leonO = new LeonOcio(oBD,seleccionado);
					jTextArea1.append("Se han introducido en la base de datos " + leonO.getContadorEvenros()
							+ " nuevas Eventos\n");
						}
				if(seleccionado.equals("Actividades")) {
					Yumping yump = new Yumping(oBD);
					jTextArea1.append("Se han introducido en la base de datos " + yump.getContadorAct()
							+ " nuevas Actividades\n");
					
				}
				if(seleccionado.equals("Rutas")) {
					LeonOcio leonO = new LeonOcio(oBD,seleccionado);
					Terranostrum Terra = new Terranostrum(oBD, seleccionado);
					int resultado = leonO.getContadorRutas() + Terra.getContadorRutas();
					jTextArea1.append("Se han introducido en la base de datos " + resultado
							+ " nuevas Rutas\n");
					
				}
				if(seleccionado.equals("Hoteles")) {
					LeonOcio leonO = new LeonOcio(oBD,seleccionado);
					jTextArea1.append("Se han introducido en la base de datos " + leonO.getContadorHotel()
							+ " nuevos Hoteles\n");
					
				}
				if(seleccionado.equals("Deportes")) {
					LeonOcio leonO = new LeonOcio(oBD,seleccionado);
					jTextArea1.append("Se han introducido en la base de datos " + leonO.getContadorDepor()
							+ " nuevas instalaciones deportivas\n");
					
				}
				if(seleccionado.equals("Parques")) {
					LeonOcio leonO = new LeonOcio(oBD,seleccionado);
					Minube minube = new Minube(oBD);
					int resultado = leonO.getContadorParques() + minube.getContadorParq();
					jTextArea1.append("Se han introducido en la base de datos " + resultado
							+ " nuevos Parques\n");
					
				}
				if(seleccionado.equals("Restaurantes")) {
					LeonOcio leonO = new LeonOcio(oBD,seleccionado);
					jTextArea1.append("Se han introducido en la base de datos " + leonO.getContadorrestau()
							+ " nuevos Restaurantes\n");
					
				}
				if(seleccionado.equals("Cultura")) {
					LeonOcio leonO = new LeonOcio(oBD,seleccionado);
					Terranostrum Terra = new Terranostrum(oBD,seleccionado);
					int resultado = leonO.getContadorCultura() + Terra.getContadorCultura();
					jTextArea1.append("Se han introducido en la base de datos " + resultado
							+ " nuevas datos de interes cultural\n");
					
				}
			
				Activar.setEnabled(true);
				Desactivar.setEnabled(false);
				 jComboBox.setEnabled(true);
				
			}
		
		};
		hilo3 = new Thread(sel);
		hilo3.start();
		
		if(seleccionado.equals("Noticias")) {
			Date d = new Date();
			jTextArea1.append("Fecha de ejecucion Web Scraper-Noticias: " + d.toString() + "\n");

		}
		if(seleccionado.equals("Eventos")) {
			Date d = new Date();
			jTextArea1.append("Fecha de ejecucion Web Scraper-Eventos: " + d.toString() + "\n");

				}
		if(seleccionado.equals("Actividades")) {
			Date d = new Date();
			jTextArea1.append("Fecha de ejecucion Web Scraper-Actividades: " + d.toString() + "\n");

			
		}
		if(seleccionado.equals("Rutas")) {
			Date d = new Date();
			jTextArea1.append("Fecha de ejecucion Web Scraper-Rutas: " + d.toString() + "\n");

			
		}
		if(seleccionado.equals("Hoteles")) {
			Date d = new Date();
			jTextArea1.append("Fecha de ejecucion Web Scraper-Hoteles: " + d.toString() + "\n");

			
		}
		if(seleccionado.equals("Deportes")) {
			Date d = new Date();
			jTextArea1.append("Fecha de ejecucion Web Scraper-Deportes: " + d.toString() + "\n");

			
		}
		if(seleccionado.equals("Parques")) {
			Date d = new Date();
			jTextArea1.append("Fecha de ejecucion Web Scraper-Parques: " + d.toString() + "\n");

			
		}
		if(seleccionado.equals("Restaurantes")) {
			Date d = new Date();
			jTextArea1.append("Fecha de ejecucion Web Scraper-Restaurantes: " + d.toString() + "\n");

			
		}
		if(seleccionado.equals("Cultura")) {
			Date d = new Date();
			jTextArea1.append("Fecha de ejecucion Web Scraper-Cultura: " + d.toString() + "\n");

		}
		}
		
		Activar.setEnabled(false);
		
		
	}

	private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton3MouseClicked
		// TODO add your handling code here:
		
			
		if(hilo.isAlive()||hilo2.isAlive()) {
			detener=false;
		}
		Desactivar.setEnabled(false);
		System.out.println(hilo.isAlive());
		while (hilo.isAlive()||hilo2.isAlive()) {}
		Activar.setEnabled(true);
		detener=true;
	
		

	}// GEN-LAST:event_jButton3MouseClicked

	BaseDatos oBD;
	/**
	 * @param args the command line arguments
	 */
	Thread hilo;
	Thread hilo2;
	Thread hilo3;
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NewJFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton Desactivar;
	private javax.swing.JButton Activar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea1;
	private JComboBox<String> jComboBox;
	private String seleccionado;
	private JLabel label;
	private boolean detener=true;
	// End of variables declaration//GEN-END:variables
}

